CanvasTest6:

<CanvasTest6>:
    RelativeLayout:
        canvas:
            Color:
                rgb:1,0,0
            Rectangle:
                size: self.size
    RelativeLayout:
        canvas:
            Color:
                rgb:1,1,1
            Rectangle:
                size: self.size
    RelativeLayout:
        canvas:
            Color:
                rgb:0,0,1
            Rectangle:
                size: self.size

<CanvasTest5>:
    BoxLayout:
        size:root.size
        Widget:
            canvas:
                Color:
                    rgb:0,1,0
                Rectangle:
                    size: self.size

        RelativeLayout:
            canvas:
                Color:
                    rgb:0,0,1
                Rectangle:
                    size: self.size
        


<CanvasTest3>:
    Button:
        pos:100,400
        text: 'A'
        on_press:root.on_button_a_click()

<CanvasTest2>:  
    canvas:
        Color:
            rgba: 1 , 0 , 0 ,.5
        Line:
            circle:(200,200,100) #center_x, center_y,radius
        Color:
            rgb: 0 , 1 , 0
        Line:
            ellipse:(500,300,100,200) #center_x, center_y,radiusx ,radiusy
            width:2
        Line:
            rectangle: (400,100,100,200) #x,y,w,h
            width:3 

<CanvasTest1>:  
    canvas:
        Line:
            points:0,self.height/2,self.width,self.height/2
        Line:
            points:self.width/2,0,self.width/2,self.height

#:set s dp(150)
<CanvasTest>:  
    canvas:
        Rectangle:
            pos:self.center_x-s/2,self.center_y-s/2
            size:s,s
        Ellipse:
            pos:200,500
            size: s,s/2
        Line:
            points:0,0,self.width/4,100,self.width/2,0,self.width*3/4,100,self.width,0
            width:2

<ImageTest@GridLayout>:
    cols:3
    Image:
        source:"images\cake.jpg"
    Image:
        source:"images\cake.jpg"
        allow_stretch: True
    Image:
        source:"images\cake.jpg"
        allow_stretch: True
        keep_ratio:False

<WeigetTest>:
    cols:3
    ToggleButton:
        text:'Off'
        on_state: root.on_toggle_button_state(self)
        size_hint:None,1
        weigth:"100dp"
    Button:
        text: "Count"
        on_press: root.on_button_click()
        disabled: not root.count_enabled
    Label:
        text: root.my_text
        font_name: 'fonts\Lcd.ttf'
        font_size: "80dp"
        color:1,0,.5,1
    Switch:
        id:on_active_slider
        on_active:root.on_switch_active(self)
        size_hint:None,1
        weigth:"100dp"
        active:True
    Slider:
        disabled:not on_active_slider.active
        id: my_slider
        min:0
        max:100
        value:50
        #on_value:root.on_slider_value(self)
        orientation: 'vertical'
    BoxLayout:
        orientation:"vertical"
        Label:
            text: str(int(my_slider.value))
        ProgressBar:
            max:100
            value: my_slider.value
    TextInput:
        id:my_text_input
        size_hint:None,1
        weigth:"100dp"
        text: 'Placeholder'
        multiline:False
        on_text_validate: root.on_text_validate(self)
    Label:
        text:root.text_input_str


<PageLayoutTest@PageLayout>:
    TestWidget:
    BoxLayoutTest:
    AnchorLayoutTest:
    GridLayoutTest:
    

<ScrollViewTest@ScrollView>:
    StackLayoutTest:
        size_hint:1,None
        height: self.minimum_height


<StackLayoutTest>:
    #left-right top-bottom
    #orientation: "rl-bt"
    #padding: ('20dp', '20dp', '20dp', '20dp')
    #spacing: '20dp', '20dp'

<GridLayoutTest@GridLayout>:
    #cols:3
    rows:2
    Button:
        text: "A"
        size_hint:None,1
        weigth:"60dp"
    BoxLayoutTest:
    Button:
        text: "C"
    Button:
        text: "D"
        size_hint:None,1
        weigth:"60dp"
    Button:
        text: "E"
    Button:
        text: "F"

<AnchorLayoutTest>:
    # right, left, center
    anchor_x: 'center'
    # bottom, top, center
    anchor_y: 'top'
    BoxLayout:
        size_hint:.2,.2
        Button:
            text: "A"
        Button:
            text: "B"

<BoxLayoutTest>:
    orientation: 'horizontal'
    Button:
        text:"A"
        #size: "100dp","60dp"
        size_hint: .5,.5
        #height: dp(60)
        #width: dp(100)
        #x,center_x ,right --for horizenral
        #y, center_y ,top  --for vertical
        pos_hint: {'center_y': .5}
    BoxLayout:
        orientation: 'vertical'
        spacing: '10dp'
        Button:
            text:"B1"
        Button:
            text:"B2"
        Button:
            text:"B3"
        Button:
            text:"B4"
        #size_hint: 1,2
    Label:
        text:"C"

<TestWidget>:
    Button:
        text: "Manav"
        size: "40dp","40dp"
        pos: "100dp","200dp" 
    Label:
        text: "Hello"
        size: "40dp","40dp"
        pos: "200dp","300dp" 
        color: 1 , 0 , 0 , 1